### PR TITLE
SGC-2276 - Add Method For Checking If A Battery Is Present

### PR DESCRIPTION
**Pull request by SlowDeepCoder**

### CODE REVIEW

**Review by bornold — CHANGES_REQUESTED** [review]
Its good!
I think, but can you add a example use in
https://github.com/abilia/system_settings_editor/blob/2a0261de986a6e4f7e04a90fb29655a813993a9a/example/lib/main.dart
as well so it is easier to test?

**Comment by bornold** [comment]
Also change version in
https://github.com/abilia/system_settings_editor/blob/2a0261de986a6e4f7e04a90fb29655a813993a9a/pubspec.yaml

**Comment by SlowDeepCoder** [comment]
Right, right!

**Review by bornold — APPROVED** [review]
Could not test because I do not have access to a large

But like it

**Pull request merged**
